# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Parwez Zafar
title: Software Engineer
email: parwezzafar3@gmail.com
# email_title: Email (Email title override)
phone: +91-7903242752
phone_title: Phone
website: https://leetcode.com/parwez01/
website_title: LeetCode

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: jekyllrb
github_username: parwez-zafar
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: md-parwez-zafar
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# leetcode_username: parwez01

# Additional icon links
additional_links:
  - title: Leetcode
    icon: fab fa-strava fa-rotate-270
    url: https://leetcode.com/parwez01/
#   - title: another link
#     icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#     url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/image.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Parwez. I am a student at Asansol Engineering College. My love for coding, problem solving and keen interest in MERN Stack web development drives my enthusiasm for the world of technology. I am committed to continuous learning and aspire to contribute effectively to dynamic projects while building a fulfilling career in software development.

  I have worked with many languages, frameworks and technologies like <mark>C</mark>, <mark>C++</mark>, <mark>JavaScript</mark>, <mark>Mongo DB</mark>, <mark>ReactJs</mark>, <mark>Angular</mark>, <mark>ExpressJs</mark>, <mark>NodeJs</mark>, <mark>REST APIs</mark>, <mark>Redux</mark>, <mark>BootStrap</mark>, <mark>Material UI</mark>, <mark>git</mark>, etc.
    
  Currently I am looking forward to opportunities which allow me to apply my problem solving and logical thinking abilities to the real world scenarios and solve real world problems.
content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Asansol Engineering College
        sub_title: B.Tech, Computer Science And Engineering
        caption: 2020 - 2024, 9.05 CGPA
        quote: >
          Asansol Engineering College (AEC) is affiliated with Maulana Abul Kalam Azad University of Technology, West Bengal
        description: | # this will include new lines to allow paragraphs
          - Learned multiple programming languages, including C++, Java, JavaScript, and more.
          - Learned how to Design and develop interactive and responsive websites, ensuring a seamless user experience.
          - Applied principles of personal development to improve time management, organization, and stress management skills, leading to increased productivity and overall personal growth.

      - layout: left
        title: GOVT NAWAL KISHORE HIGH SCHOOL.
        sub_title: Higher Secondary
        caption: 2017 - 2019, 83%
        quote: >
          GOVT NAWAL KISHORE HIGH SCHOOL is affiliated with Bihar School Examination Board (BSEB)
        description: | # this will include new lines to allow paragraphs
          - Completed Intermediate grade with a focus on science, including physics, chemistry, and mathematics.
          - Developed a foundation in science and mathematics, which laid the groundwork for pursuing higher education in a technical field.
          - Achieved the prestigious first rank in the science results, demonstrating exceptional dedication and mastery of the subject matter.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Trustt (formerly novopay)
        sub_title: Software Development Engineer Intern
        caption: February 2024 - present
        # link: Link to company (optional)
        quote: >
          Working as a web Developer Intern
        description: | # this will include new lines to allow paragraphs
          - Working on <mark>Novopay Platform Web App</mark>: Contributing to the development and maintenance of the Novopay platform web application using <mark>Angular</mark>.
          - <mark>Resolved Active Link Bug</mark>: Successfully diagnosed and rectified a critical issue where the sidebar item failed to highlight upon activation, enhancing user navigation and experience.


          ---

      - layout: left
        title: Neonflake Enterprises
        sub_title: Software Engineer Intern
        caption: October 2023 - January 2024
        # link: Link to company (optional)
        quote: >
          Working as a Full-Stack Developer Intern
        description: | # this will include new lines to allow paragraphs
          - Developed and maintained an admin section within a <mark>MERN stack</mark> (MongoDB, Express.js, Node.js, React.Js) website for a client.
          - Implemented a <mark>Forgot Password</mark> functionality for users, enhancing the security and usability of the website.
          - Removed redundant website sections to improve performance and user experience, utilized <mark>JavaScript</mark> and ReactJs to improve performance.
          - Added new features and functionalities to meet <mark>client requirements</mark>, enhanced user engagement and site functionality.

          ---

      - layout: left
        title: Celebal Technologies
        sub_title: Celebal Summer Intern
        caption: June 2023 - August 2023
        # link: https://github.com/parwez-zafar/weather-app
        # link: Link to company (optional)
        quote: >
          Received training and hands-on experience in MERN stack development
        description: | # this will include new lines to allow paragraphs
          - Successfully completed a task to create a dynamic weather website using MERN stack technologies (MongoDB, Express.js, Node.js, React).
          - Independently designed and implemented a responsive, real-time weather application, providing users with up-to-date weather information and forecasts.
          - Utilized openweathermap API to fetch weather data and develop dynamic, interactive data visualization components.
          - Gained valuable experience in <mark>Mongo DB</mark>, <mark>ReactJs</mark>, <mark>ExpressJs</mark>, <mark>NodeJs</mark>, <mark>Redux</mark>.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border:
        #   weak # Value of `weak` will display a weak border below this item. # Any
        # other value (or no value) means no border will be displayed
        title: Ecommerce Website
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # github: https://github.com/parwez-zafar/Ecommerce-Website
        additional_links:
          - title: Github
            icon: fab fa-github
            url: https://github.com/parwez-zafar/Ecommerce-Website
          # - title: Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          A FullStack Ecommerce Website having User and Admin panel.
        description: | # this will include new lines to allow paragraphs
          - Designed and developed a full-featured Ecommerce website with separate <mark>admin</mark> and <mark>user</mark> panels from scratch.
          - Implemented essential Ecommerce functionalities, including user registration and authentication, <mark>product catalog</mark>, shopping cart, <mark>payment processing</mark>, user reviews, <mark>order management</mark> etc.
          - Developed a user-friendly  <mark>admin panel</mark> for managing products, orders, and user accounts with appropriate  <mark>access controls</mark>.
          - Integrated secure <mark>payment gateways</mark> and ensured data privacy and security.
          - This personal project showcases my proficiency in full-stack web development, database management, and user interface design.
          - TechStack :- <mark>Mongo DB</mark>, <mark>ExpressJs</mark>, <mark>ReactJs</mark>, <mark>NodeJs</mark>, <mark>Redux</mark>, <mark>REST APIs</mark>, <mark>Material UI</mark>, <mark>JsonWebToken</mark>.


          ---------------

      - layout: left
        border:
          weak # Value of `weak` will display a weak border below this item. # Any
          # other value (or no value) means no border will be displayed
        title: Food Delivery Website
        link: https://extraordinary-profiterole-c3cb99.netlify.app/
        # github: https://github.com/parwez-zafar/Ecommerce-Website
        additional_links:
          - title: Github Client
            icon: fab fa-github
            url: https://github.com/parwez-zafar/food_web_app_client
          - title: Github Server
            icon: fab fa-github
            url: https://github.com/parwez-zafar/food_web_app_server
        quote: >
          A FullStack Food Delivery Website.
        description: | # this will include new lines to allow paragraphs
          - Designed and developed a Food Delivery Website using the MERN stack (MongoDB, ExpressJS, ReactJS, NodeJS).
          - Implemented secure user authentication with JSON Web Tokens (JWT) for signup and login functionality.
          - Built a RESTful API for handling food orders, menu items, and user profiles.
          - Utilized MongoDB to efficiently store and retrieve data, ensuring optimal performance and scalability.
          - TechStack :- <mark>Mongo DB</mark>, <mark>ExpressJs</mark>, <mark>ReactJs</mark>, <mark>NodeJs</mark>, <mark>Redux</mark>, <mark>REST APIs</mark>, <mark>Bootstrap</mark>.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Skills**
      - <mark>Problem Solving</mark>, <mark>C++</mark>, <mark>JavaScript</mark>, <mark>Java(Basics)</mark>, <mark>Rest Api</mark>, <mark>ReactJs</mark>, <mark>NodeJs</mark>, <mark>ExpressJs</mark>, <mark>Redux</mark>

      **Acheivements**
      - 1660 rating ([ <mark>LeetCode</mark> ](https://leetcode.com/parwez01/) 650+ Problems)
      - 2 Star ([ <mark>CodeChef</mark> ](https://www.codechef.com/users/parwez_01) max 1455)
      - 5 Star ([<mark>Hackerrank</mark> ](https://www.hackerrank.com/profile/parwezzafar3) c++)
      - 1000+ Programming questions solved on Online judges like LeetCode, CodeChef, CodeForces etc.
      - first rank in the science results in Intermediate

      **COURSE WORK**
        - Data Structures & Algorithm ([ <mark>Certificate</mark> ](https://www.udemy.com/certificate/UC-a1b7f681-7a57-41e8-a5b2-f8275cbd28bb/) 4.7 star rated course on Udemy by BY <mark>Abdul Bari</mark>)
        - Object Oriented Programming
        - Operating System
        - Database And Management System
        - Computer Networks
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
